'use client';
import { useEffect, useRef, useState } from 'react';
import { ArrowDownToLine, FileText, Layers, Upload } from 'lucide-react';
import { Slider } from '@/components/ui/slider';
import { NativeSelect } from '@/components/ui/native-select';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { comparable, gradeNames, metrics, parsePrediction, parseRuns, predictedGrade, reportText } from '../../lib/analysis';
import type { Prediction, Quality, Run } from '../../lib/analysis';

export function download(name:string, text:string, type='application/json') {
 const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
}
async function readJSON(file:File) {if(file.size>15*1024*1024)throw Error('JSON files must be under 15 MB.');return JSON.parse(await file.text());}
export function Heatmap({map,opacity}:{map:NonNullable<Prediction['heatmap']>;opacity:number}) {
 const ref=useRef<HTMLCanvasElement>(null);
 useEffect(()=>{
  const canvas=ref.current;if(!canvas)return;canvas.width=map.values[0].length;canvas.height=map.values.length;
  const ctx=canvas.getContext('2d');if(!ctx)return;const pixels=ctx.createImageData(canvas.width,canvas.height);
  map.values.flat().forEach((v,i)=>{pixels.data[i*4]=255;pixels.data[i*4+1]=Math.round(220*(1-v));pixels.data[i*4+2]=0;pixels.data[i*4+3]=Math.round(v*255);});ctx.putImageData(pixels,0,0);
 },[map]);
 return <canvas ref={ref} className="heatmap-overlay" style={{opacity}} aria-label="Imported model attribution overlay; not a lesion segmentation"/>;
}
type Record = {id:string;eye:string;status:string;image?:string;imageSha256?:string;review?:string;notes?:string;qualityCheck?:Quality;analysis?:Prediction};
export function CaseTools({record,onAnalysis}:{record:Record;onAnalysis:(value:Prediction|undefined)=>void}) {
 const [error,setError]=useState(''),[report,setReport]=useState<string|null>(null),[threshold,setThreshold]=useState(70);
 const p=record.analysis,q=record.qualityCheck;
 useEffect(()=>{setError('');setReport(null);},[record.id]);
 useEffect(()=>{setReport(null);},[record.analysis,record.notes,record.review,record.status]);
 const confidence=p ? Math.max(...p.probabilities)*100 : null;
 return <section className="case-tools">
  <article className="panel feature-panel"><div className="feature-heading"><div><span className="eyebrow">01 / IMAGE QUALITY</span><h2>Quality before interpretation.</h2></div><span className="outline-badge">LOCAL HEURISTIC</span></div>{q ? <><div className={`quality-verdict ${q.flags.length?'flagged':''}`}>{q.flags.length ? 'Check image quality' : 'No heuristic flags'}<small>These signals do not establish clinical gradability or confirm a fundus image.</small></div><div className="signal-grid">{[['Resolution',`${q.width} × ${q.height}`],['Exposure',`${q.brightness.toFixed(0)} / 255`],['Contrast',q.contrast.toFixed(1)],['Sharpness',q.sharpness.toFixed(1)],['Illuminated area',`${(q.coverage*100).toFixed(0)}%`],['Clipped highlights',`${(q.clipping*100).toFixed(1)}%`]].map(([name,value])=><div key={name}><span>{name}</span><strong>{value}</strong></div>)}</div>{q.flags.length>0&&<ul className="flag-list">{q.flags.map(f=><li key={f}>{f}</li>)}</ul>}<details><summary>How these checks work</summary><p>Brightness and contrast are measured on pixels above luminance 10. Sharpness is Laplacian variance after resizing to at most 512 pixels. Noise and image content affect these signals.</p><p>Flags: shorter edge &lt;512 px; illuminated area &lt;35%; brightness &lt;45 or &gt;210; highlights &gt;10%; contrast &lt;20; sharpness &lt;60. These fixed thresholds are unvalidated and camera-dependent.</p></details></> : <div className="feature-empty">Open an image to measure exposure, contrast, sharpness, resolution, and illuminated area. Sample cases have no image to analyze.</div>}</article>
  <article className="panel feature-panel"><div className="feature-heading"><div><span className="eyebrow">02 / CONFIDENCE & EXPLANATION</span><h2>Inspect the model’s output.</h2></div><Layers size={22}/></div><p className="feature-description">Import an output from a trained model for this exact image. Attribution highlights model influence; it is not a verified lesion map.</p>{p ? <><div className="confidence-top"><strong>{confidence!.toFixed(1)}<small>%</small></strong><div><span>Top-class probability</span><p>{gradeNames[predictedGrade(p.probabilities)]}</p></div></div><div className="probabilities">{p.probabilities.map((value,i)=><div key={i}><span>{i} · {gradeNames[i]}</span><meter min={0} max={1} value={value}/><b>{(value*100).toFixed(1)}%</b></div>)}</div><label className="threshold-label">Review threshold: {threshold}%<Slider aria-label="Confidence review threshold" value={[threshold]} onValueChange={v=>setThreshold(Array.isArray(v)?v[0]:v)} min={0} max={100}/></label><p className="quality-verdict">{confidence!<threshold?'Below threshold — manual review required':'Above threshold — human review still required'}</p><p className="feature-description">Model: {p.model}<br/>Calibration declaration: {p.calibration}<br/>Heatmap: {p.heatmap?.method ?? 'Not supplied'}. Imported declarations are not independently verified. Probability is not a guarantee of correctness.</p><button className="secondary" onClick={()=>onAnalysis(undefined)}>Remove imported output</button></> : <div className="feature-empty">No model output yet. Confidence and attribution remain unavailable until a trained model’s results are imported.</div>}<label className={`secondary file-button ${!record.imageSha256?'unavailable':''}`}><Upload size={16}/> Import prediction JSON<input type="file" accept=".json,application/json" disabled={!record.imageSha256} onChange={async e=>{const file=e.target.files?.[0];e.target.value='';if(!file||!record.imageSha256)return;try{const result=parsePrediction(await readJSON(file),record.imageSha256);onAnalysis(result);setError('');}catch(err){setError(err instanceof Error?err.message:'Unable to import output.');}}}/></label>{error&&<p className="import-error" role="alert">{error}</p>}<details><summary>Prediction format & image identity</summary><p>Export the case JSON to obtain this image’s SHA-256. Heatmaps must be inverse-mapped to the full original image, including any crop and padding.</p><pre>{JSON.stringify({imageSha256:record.imageSha256??'SHA256_OF_ORIGINAL_FILE',model:'model-version',probabilities:[.05,.1,.7,.1,.05],calibration:'uncalibrated',heatmap:{method:'Grad-CAM',alignment:'original-image',values:[[0,.2],[.6,1]]}},null,2)}</pre><p>Example values explain the file format only; they are not predictions.</p></details></article>
  <article className="panel feature-panel report-tools"><div className="feature-heading"><div><span className="eyebrow">03 / STRUCTURED REPORT</span><h2>A record of the review.</h2></div><FileText size={22}/></div><p className="feature-description">Generate a clinical-style research report from available image checks, imported predictions, and reviewer notes. Missing findings stay explicitly unassessed.</p><button className="primary" onClick={()=>setReport(reportText(record,new Date().toISOString()))}><FileText size={16}/> Generate report</button>{report&&<><div className="report-actions"><button className="secondary" onClick={()=>download(`${record.id}-research-report.txt`,report,'text/plain')}><ArrowDownToLine size={16}/> Download report</button><button className="secondary" onClick={()=>window.print()}>Print / Save as PDF</button></div><pre id="research-report">{report}</pre></>}</article>
 </section>;
}
const fmt=(n:number|null)=>n===null?'Not defined':n.toFixed(3);
export function EvaluationTools({runs,onRuns}:{runs:Run[];onRuns:(runs:Run[])=>void}) {
 const [error,setError]=useState(''),[selected,setSelected]=useState(''),[baseline,setBaseline]=useState(''),[idridOnly,setIdridOnly]=useState(false),[kind,setKind]=useState('all'),[trueGrade,setTrueGrade]=useState('all'),[minimum,setMinimum]=useState(0),[search,setSearch]=useState('');
 const visible=runs.filter(r=>!idridOnly||(r.dataset.toLowerCase()==='idrid'&&r.external));
 const run=visible.find(r=>r.id===selected)??visible[0];
 const base=runs.find(r=>r.id===baseline)??runs[0];
 const m=run?metrics(run.rows):null;
 const errors=run?.rows.filter(r=>r.predictedGrade!==r.trueGrade&&(trueGrade==='all'||r.trueGrade===Number(trueGrade))&&(kind==='all'||(kind==='under'&&r.predictedGrade<r.trueGrade)||(kind==='over'&&r.predictedGrade>r.trueGrade)||(kind==='large'&&Math.abs(r.predictedGrade-r.trueGrade)>=2))&&(!minimum||(r.probabilities&&Math.max(...r.probabilities)*100>=minimum))&&r.id.toLowerCase().includes(search.toLowerCase()))??[];
 const rowsSample={runs:[{id:'example-baseline',model:'Example model — not trained',variant:'Global only',dataset:'SYNTHETIC',split:'test',cohort:'format-demo',external:false,overlapChecked:false,rows:[{id:'sample-1',trueGrade:0,predictedGrade:0,probabilities:[.8,.1,.05,.03,.02]},{id:'sample-2',trueGrade:3,predictedGrade:1,probabilities:[.1,.6,.15,.1,.05]}]}]};
 return <section className="evaluation-tools"><div className="panel feature-panel"><div className="feature-heading"><div><span className="eyebrow">EXPERIMENT WORKBENCH</span><h2>Compare evidence, not claims.</h2></div><span className="outline-badge">{runs.length} IMPORTED RUNS</span></div><p className="feature-description">Import labeled predictions to calculate metrics, compare ablations, inspect external IDRiD results, and investigate failures. No model training or IDRiD inference is performed here.</p><div className="report-actions"><label className="primary file-button"><Upload size={16}/> Import evaluation JSON<input type="file" accept=".json,application/json" onChange={async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;try{const parsed=parseRuns(await readJSON(file));onRuns(parsed);setSelected(parsed[0].id);setBaseline(parsed[0].id);setError('');setIdridOnly(false);setSearch('');setMinimum(0);setTrueGrade('all');setKind('all');}catch(err){setError(err instanceof Error?err.message:'Invalid evaluation file.');}}}/></label><button className="secondary" onClick={()=>download('evaluation-format-example.json',JSON.stringify(rowsSample,null,2))}>Download format example</button>{runs.length>0&&<button className="secondary" onClick={()=>download('evaluation-runs.json',JSON.stringify({runs},null,2))}>Export runs</button>}</div><p className="feature-description">Import replaces the current runs. Files remain in browser memory; export before refreshing. Format examples are synthetic and never loaded automatically.</p>{error&&<p role="alert" className="import-error">{error}</p>}<details><summary>Data requirements & metric definitions</summary><p>Each run needs a unique ID, model, variant, dataset, split, cohort, external flag, overlapChecked flag, and unique labeled rows. Grades are integers 0–4. Optional five-class probabilities must sum to 1 and match predictedGrade by argmax.</p><p>QWK uses squared grade disagreement; undefined denominators display “Not defined”. Macro F1 averages all five grades, with missing-class F1 set to zero. ECE uses ten equal-width probability bins and only rows with probabilities. No confidence intervals or clinical operating points are estimated.</p><p>External status and overlap checks are importer declarations, not independent evidence. Keep test data untouched during model selection. Patient-level leakage and foundation-model pretraining overlap require a separate audit.</p></details></div>
 <div className="panel feature-panel"><div className="feature-heading"><div><span className="eyebrow">04 / MODEL COMPARISON & ABLATION</span><h2>Same cohort. Clear differences.</h2></div></div>{base?<><label className="control-label">Baseline<NativeSelect value={base.id} onChange={e=>setBaseline(e.target.value)}>{runs.map(r=><option key={r.id} value={r.id}>{r.model} · {r.variant} · {r.id}</option>)}</NativeSelect></label><Table><TableHeader><TableRow>{['Run / variant','Dataset / split','N','QWK','Macro F1','Δ QWK vs baseline'].map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{runs.map(r=>{const s=metrics(r.rows),b=metrics(base.rows);const matched=comparable(base,r);return <TableRow key={r.id}><TableCell>{r.model}<small>{r.variant} · {r.id}</small></TableCell><TableCell>{r.dataset} / {r.split}</TableCell><TableCell>{s.n}</TableCell><TableCell>{fmt(s.qwk)}</TableCell><TableCell>{fmt(s.macroF1)}</TableCell><TableCell>{matched?(s.qwk!==null&&b.qwk!==null?(s.qwk-b.qwk).toFixed(3):'Not defined'):'Different cohort'}</TableCell></TableRow>;})}</TableBody></Table><p className="feature-description">Deltas require identical dataset, split, cohort, external status, case IDs, and labels. This checks comparability, not statistical significance or controlled training conditions.</p></>:<div className="feature-empty">Import baseline and variant runs to compare actual results.</div>}</div>
 <div className="panel feature-panel"><div className="feature-heading"><div><span className="eyebrow">05 / EXTERNAL VALIDATION</span><h2>Performance beyond the training source.</h2></div><button className={idridOnly?'primary':'secondary'} aria-pressed={idridOnly} onClick={()=>setIdridOnly(!idridOnly)}>External IDRiD only</button></div>{run&&m?<><label className="control-label">Evaluation run<NativeSelect value={run.id} onChange={e=>setSelected(e.target.value)}>{visible.map(r=><option key={r.id} value={r.id}>{r.id} · {r.dataset}</option>)}</NativeSelect></label><p className="sample-note">{run.dataset} / {run.split} / {run.cohort} · {run.external?'Declared external':'Internal / unspecified externality'} · {run.overlapChecked?'Overlap check declared':'Overlap not checked — independence unverified'}</p><div className="metric-grid">{[['QWK',fmt(m.qwk)],['Macro F1',fmt(m.macroF1)],['Accuracy',m.accuracy===null?'—':`${(m.accuracy*100).toFixed(1)}%`],['Mean absolute grade error',fmt(m.mae)],['Calibration ECE',fmt(m.ece)],['Evaluated images',String(m.n)]].map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div><p className="feature-description">Calibration uses {m.scored} of {m.n} rows. Small cohorts and absent grades can make metrics unstable.</p><h3>Confusion matrix <small>Rows = true grade · columns = predicted grade</small></h3><Table><TableHeader><TableRow><TableHead>True / predicted</TableHead>{gradeNames.map((_,i)=><TableHead key={i}>{i}</TableHead>)}<TableHead>Recall</TableHead><TableHead>Support</TableHead></TableRow></TableHeader><TableBody>{m.matrix.map((row,i)=><TableRow key={i}><TableCell>{i} · {gradeNames[i]}</TableCell>{row.map((v,j)=><TableCell key={j} className={i===j?'matrix-correct':''}>{v}</TableCell>)}<TableCell>{m.recalls[i]===null?'No examples':`${(m.recalls[i]!*100).toFixed(1)}%`}</TableCell><TableCell>{m.actual[i]}</TableCell></TableRow>)}</TableBody></Table></>:<div className="feature-empty">{idridOnly?'No imported external IDRiD run. Set dataset to “IDRiD” and external to true only for an independently held-out evaluation.':'Import labeled results to view validation metrics.'}</div>}</div>
 <div className="panel feature-panel"><div className="feature-heading"><div><span className="eyebrow">06 / ERROR ANALYSIS</span><h2>Understand what went wrong.</h2></div><span className="outline-badge">{errors.length} MATCHING ERRORS</span></div><div className="error-filters"><label>Case ID<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search failures"/></label><label>Error type<NativeSelect value={kind} onChange={e=>setKind(e.target.value)}><option value="all">All errors</option><option value="under">Undergraded</option><option value="over">Overgraded</option><option value="large">At least 2 grades apart</option></NativeSelect></label><label>True grade<NativeSelect value={trueGrade} onChange={e=>setTrueGrade(e.target.value)}><option value="all">All grades</option>{gradeNames.map((g,i)=><option key={i} value={i}>{i} · {g}</option>)}</NativeSelect></label><label>Minimum confidence %<input type="number" min={0} max={100} value={minimum} onChange={e=>setMinimum(Math.max(0,Math.min(100,Number(e.target.value)||0)))}/></label></div>{run?<><Table><TableHeader><TableRow>{['Case','True grade','Predicted','Grade difference','Confidence'].map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{errors.slice(0,100).map(r=><TableRow key={r.id}><TableCell>{r.id}</TableCell><TableCell>{r.trueGrade}</TableCell><TableCell>{r.predictedGrade}</TableCell><TableCell>{r.predictedGrade-r.trueGrade}</TableCell><TableCell>{r.probabilities?`${(Math.max(...r.probabilities)*100).toFixed(1)}%`:'Not supplied'}</TableCell></TableRow>)}</TableBody></Table>{!errors.length&&<p className="feature-empty">No errors match these filters.</p>}<p className="feature-description">Showing up to 100 rows. A positive confidence filter excludes rows without probabilities.</p><button className="secondary" disabled={!errors.length} onClick={()=>download(`${run.id.replace(/[^a-zA-Z0-9_-]/g,'_')}-errors.json`,JSON.stringify({run:run.id,filters:{kind,trueGrade,minimum,search},errors},null,2))}>Export all matching errors</button></>:<p className="feature-empty">Error analysis becomes available after importing a labeled evaluation run.</p>}</div>
 </section>;
}
